[project]
name = "agentic-rag-pipelines"
version = "0.1.0"
description = ""
authors = [
    {name = "AdityaC4",email = "adityapchaudhari@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "langgraph (>=0.3.34,<0.4.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
